name: geodude
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - pandas
  - matplotlib
  - seaborn
  - pylops
  - ipython
  - jupyter
  - cudatoolkit=11.3
  - pytorch==1.10.1
  - lightgbm
  - tqdm
  - pip:
    - pymupdf
    - pypdf
    - pygpt4all
    - git+https://github.com/jerryjliu/llama_index.git
    - langchain
    - sentence_transformers
    - accelerate
    - openpyxl
    - gradio